version: '3'
services:
  tracker:
    build: ./
    env_file: .env
    links:
      - kafka
  kafka:
      image: spotify/kafka
      environment:
        - ADVERTISED_PORT=9092
        - ADVERTISED_HOST=kafka
